server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker-logs
          __path__: /var/lib/docker/containers/*/*-json.log

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs: attrs
            tag: attrs.tag
            time: time

      - regex:
          expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
          source: "tag"

      - labels:
          stream:
          image_name:
          container_name:
          container_id:

      - output:
          source: output

      # Фильтр для логов только от backend контейнера
      - match:
          selector: '{container_name="backend"}'
          stages:
            - json:
                expressions:
                  level: level
                  message: msg
                  timestamp: time
            - labels:
                level:
            - timestamp:
                source: timestamp
                format: RFC3339